### PR TITLE
Add GPG signature and checksum checking

### PR DESCRIPTION
**Pull request by specing**
Zzzzzzzzz #38

### CODE REVIEW

**Comment by globalcitizen** [comment]
I like the idea and applaud the effort, but we've been holding out for a 'proper solution' (see https://bugs.gentoo.org/show_bug.cgi?id=453620 for explanation and progress) and accepting this patch means everyone has to add a manual process to their usage.

I guess my resistance to applying this is therefore twofold:

(1) How is this (not) going to work with the emerging 'proper' solution?
(2) How can we remove the manual process hassle for current users?

If you can investigate/solve those two issues I'm happy to apply.

**Comment by specing** [comment]
That bug has been open for over two years now and I don't want people to run unsigned code just because we are waiting on some "proper solution". As for it being manual... well using emerge-webrsync (and you should be using it) with GPG requires manual setup as well (though with seperate gpg directory).

(1) After it finaly emerges after X more years, we'll fix the script.
(2) Embed the key into the script?

**Comment by globalcitizen** [comment]
Sure, we can waive (1). While (2) is really not good practice, you are right that waiting may just be another two years... so... if you want to implement the embedded key, including some form of meaningful failure messages for the case that the key has expired (abort) or the binary is signed by a different key (abort), and some option to override/skip the whole GPG business, I'd be happy to merge. Sorry to be pedantic. :)

**Comment by specing** [comment]
I only suggested embedding the key because you asked for it, but I don't think that is good practise.

http://www.gentoo.org/doc/en/handbook/2006.0/handbook-x86.xml?full=1#webrsync-gpg

**Comment by globalcitizen** [comment]
You're right that it's not ideal. Unfortunately, we have a strong competing concern here: we can't assume people are on a Gentoo host, so `emerge-webrsync` is not something we are able to rely on outside of the container for the purposes of container setup. This is part of the reason why I was waiting for the 'proper solution'... because anything hacky and temporary that meets our portability requirements is by definition hacky and temporary.

**Comment by specing** [comment]
We would not be relying on emerge-webrsync. I only linked it for the GPG setup instructions, which are "pretty much" the same:
gpg --keyserver subkeys.pgp.net --recv-keys 0xBB572E0E2D182910
and you are done

**Comment by specing** [comment]
... Im going to add this into instructions and provide an env var for alternate GPG home
and add signature checking for portage download.

**Comment by specing** [comment]
done.

**Comment by specing** [comment]
Zzzzzzzzzz

**Comment by globalcitizen** [comment]
Sorry I'm stuck in China with crap to nonexistent internet and am quite
busy. I'll merge when I get out to Europe in a week or two. It's really
that bad. Apologies for the delay!

- Walter

**Pull request merged**
